/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MethodRouteImport } from './routes/method'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'
import { Route as PayPaymentIdRouteImport } from './routes/pay.$paymentId'
import { Route as OnboardingDiagnosticRouteImport } from './routes/onboarding.diagnostic'
import { Route as OnboardingBandRouteImport } from './routes/onboarding.band'
import { Route as AppVocabularyRouteImport } from './routes/app.vocabulary'
import { Route as AppSessionRouteImport } from './routes/app.session'
import { Route as AppLexiconRouteImport } from './routes/app.lexicon'
import { Route as AppGrammarRouteImport } from './routes/app.grammar'
import { Route as TestsTestIdIndexRouteImport } from './routes/tests.$testId.index'
import { Route as OnboardingDiagnosticIndexRouteImport } from './routes/onboarding.diagnostic.index'
import { Route as AppSessionIndexRouteImport } from './routes/app.session.index'
import { Route as AppLexiconIndexRouteImport } from './routes/app.lexicon.index'
import { Route as AppGrammarIndexRouteImport } from './routes/app.grammar.index'
import { Route as TestsTestIdResultsRouteImport } from './routes/tests.$testId.results'
import { Route as OnboardingDiagnosticWritingRouteImport } from './routes/onboarding.diagnostic.writing'
import { Route as OnboardingDiagnosticResultRouteImport } from './routes/onboarding.diagnostic.result'
import { Route as OnboardingDiagnosticReadingRouteImport } from './routes/onboarding.diagnostic.reading'
import { Route as OnboardingDiagnosticListeningRouteImport } from './routes/onboarding.diagnostic.listening'
import { Route as AppLexiconWeekRouteImport } from './routes/app.lexicon.$week'
import { Route as AppGrammarWeekRouteImport } from './routes/app.grammar.$week'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => TestsRoute,
} as any)
const PayPaymentIdRoute = PayPaymentIdRouteImport.update({
  id: '/pay/$paymentId',
  path: '/pay/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDiagnosticRoute = OnboardingDiagnosticRouteImport.update({
  id: '/onboarding/diagnostic',
  path: '/onboarding/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBandRoute = OnboardingBandRouteImport.update({
  id: '/onboarding/band',
  path: '/onboarding/band',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVocabularyRoute = AppVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppLexiconRoute = AppLexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => AppRoute,
} as any)
const AppGrammarRoute = AppGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AppRoute,
} as any)
const TestsTestIdIndexRoute = TestsTestIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsTestIdRoute,
} as any)
const OnboardingDiagnosticIndexRoute =
  OnboardingDiagnosticIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OnboardingDiagnosticRoute,
  } as any)
const AppSessionIndexRoute = AppSessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSessionRoute,
} as any)
const AppLexiconIndexRoute = AppLexiconIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLexiconRoute,
} as any)
const AppGrammarIndexRoute = AppGrammarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGrammarRoute,
} as any)
const TestsTestIdResultsRoute = TestsTestIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TestsTestIdRoute,
} as any)
const OnboardingDiagnosticWritingRoute =
  OnboardingDiagnosticWritingRouteImport.update({
    id: '/writing',
    path: '/writing',
    getParentRoute: () => OnboardingDiagnosticRoute,
  } as any)
const OnboardingDiagnosticResultRoute =
  OnboardingDiagnosticResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => OnboardingDiagnosticRoute,
  } as any)
const OnboardingDiagnosticReadingRoute =
  OnboardingDiagnosticReadingRouteImport.update({
    id: '/reading',
    path: '/reading',
    getParentRoute: () => OnboardingDiagnosticRoute,
  } as any)
const OnboardingDiagnosticListeningRoute =
  OnboardingDiagnosticListeningRouteImport.update({
    id: '/listening',
    path: '/listening',
    getParentRoute: () => OnboardingDiagnosticRoute,
  } as any)
const AppLexiconWeekRoute = AppLexiconWeekRouteImport.update({
  id: '/$week',
  path: '/$week',
  getParentRoute: () => AppLexiconRoute,
} as any)
const AppGrammarWeekRoute = AppGrammarWeekRouteImport.update({
  id: '/$week',
  path: '/$week',
  getParentRoute: () => AppGrammarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/atlas': typeof AtlasRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/tests': typeof TestsRouteWithChildren
  '/app/grammar': typeof AppGrammarRouteWithChildren
  '/app/lexicon': typeof AppLexiconRouteWithChildren
  '/app/session': typeof AppSessionRouteWithChildren
  '/app/vocabulary': typeof AppVocabularyRoute
  '/onboarding/band': typeof OnboardingBandRoute
  '/onboarding/diagnostic': typeof OnboardingDiagnosticRouteWithChildren
  '/pay/$paymentId': typeof PayPaymentIdRoute
  '/tests/$testId': typeof TestsTestIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/app/grammar/$week': typeof AppGrammarWeekRoute
  '/app/lexicon/$week': typeof AppLexiconWeekRoute
  '/onboarding/diagnostic/listening': typeof OnboardingDiagnosticListeningRoute
  '/onboarding/diagnostic/reading': typeof OnboardingDiagnosticReadingRoute
  '/onboarding/diagnostic/result': typeof OnboardingDiagnosticResultRoute
  '/onboarding/diagnostic/writing': typeof OnboardingDiagnosticWritingRoute
  '/tests/$testId/results': typeof TestsTestIdResultsRoute
  '/app/grammar/': typeof AppGrammarIndexRoute
  '/app/lexicon/': typeof AppLexiconIndexRoute
  '/app/session/': typeof AppSessionIndexRoute
  '/onboarding/diagnostic/': typeof OnboardingDiagnosticIndexRoute
  '/tests/$testId/': typeof TestsTestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/app/vocabulary': typeof AppVocabularyRoute
  '/onboarding/band': typeof OnboardingBandRoute
  '/pay/$paymentId': typeof PayPaymentIdRoute
  '/app': typeof AppIndexRoute
  '/tests': typeof TestsIndexRoute
  '/app/grammar/$week': typeof AppGrammarWeekRoute
  '/app/lexicon/$week': typeof AppLexiconWeekRoute
  '/onboarding/diagnostic/listening': typeof OnboardingDiagnosticListeningRoute
  '/onboarding/diagnostic/reading': typeof OnboardingDiagnosticReadingRoute
  '/onboarding/diagnostic/result': typeof OnboardingDiagnosticResultRoute
  '/onboarding/diagnostic/writing': typeof OnboardingDiagnosticWritingRoute
  '/tests/$testId/results': typeof TestsTestIdResultsRoute
  '/app/grammar': typeof AppGrammarIndexRoute
  '/app/lexicon': typeof AppLexiconIndexRoute
  '/app/session': typeof AppSessionIndexRoute
  '/onboarding/diagnostic': typeof OnboardingDiagnosticIndexRoute
  '/tests/$testId': typeof TestsTestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/atlas': typeof AtlasRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/tests': typeof TestsRouteWithChildren
  '/app/grammar': typeof AppGrammarRouteWithChildren
  '/app/lexicon': typeof AppLexiconRouteWithChildren
  '/app/session': typeof AppSessionRouteWithChildren
  '/app/vocabulary': typeof AppVocabularyRoute
  '/onboarding/band': typeof OnboardingBandRoute
  '/onboarding/diagnostic': typeof OnboardingDiagnosticRouteWithChildren
  '/pay/$paymentId': typeof PayPaymentIdRoute
  '/tests/$testId': typeof TestsTestIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/app/grammar/$week': typeof AppGrammarWeekRoute
  '/app/lexicon/$week': typeof AppLexiconWeekRoute
  '/onboarding/diagnostic/listening': typeof OnboardingDiagnosticListeningRoute
  '/onboarding/diagnostic/reading': typeof OnboardingDiagnosticReadingRoute
  '/onboarding/diagnostic/result': typeof OnboardingDiagnosticResultRoute
  '/onboarding/diagnostic/writing': typeof OnboardingDiagnosticWritingRoute
  '/tests/$testId/results': typeof TestsTestIdResultsRoute
  '/app/grammar/': typeof AppGrammarIndexRoute
  '/app/lexicon/': typeof AppLexiconIndexRoute
  '/app/session/': typeof AppSessionIndexRoute
  '/onboarding/diagnostic/': typeof OnboardingDiagnosticIndexRoute
  '/tests/$testId/': typeof TestsTestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/atlas'
    | '/login'
    | '/method'
    | '/pricing'
    | '/profile'
    | '/signup'
    | '/study'
    | '/tests'
    | '/app/grammar'
    | '/app/lexicon'
    | '/app/session'
    | '/app/vocabulary'
    | '/onboarding/band'
    | '/onboarding/diagnostic'
    | '/pay/$paymentId'
    | '/tests/$testId'
    | '/app/'
    | '/tests/'
    | '/app/grammar/$week'
    | '/app/lexicon/$week'
    | '/onboarding/diagnostic/listening'
    | '/onboarding/diagnostic/reading'
    | '/onboarding/diagnostic/result'
    | '/onboarding/diagnostic/writing'
    | '/tests/$testId/results'
    | '/app/grammar/'
    | '/app/lexicon/'
    | '/app/session/'
    | '/onboarding/diagnostic/'
    | '/tests/$testId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/login'
    | '/method'
    | '/pricing'
    | '/profile'
    | '/signup'
    | '/study'
    | '/app/vocabulary'
    | '/onboarding/band'
    | '/pay/$paymentId'
    | '/app'
    | '/tests'
    | '/app/grammar/$week'
    | '/app/lexicon/$week'
    | '/onboarding/diagnostic/listening'
    | '/onboarding/diagnostic/reading'
    | '/onboarding/diagnostic/result'
    | '/onboarding/diagnostic/writing'
    | '/tests/$testId/results'
    | '/app/grammar'
    | '/app/lexicon'
    | '/app/session'
    | '/onboarding/diagnostic'
    | '/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/atlas'
    | '/login'
    | '/method'
    | '/pricing'
    | '/profile'
    | '/signup'
    | '/study'
    | '/tests'
    | '/app/grammar'
    | '/app/lexicon'
    | '/app/session'
    | '/app/vocabulary'
    | '/onboarding/band'
    | '/onboarding/diagnostic'
    | '/pay/$paymentId'
    | '/tests/$testId'
    | '/app/'
    | '/tests/'
    | '/app/grammar/$week'
    | '/app/lexicon/$week'
    | '/onboarding/diagnostic/listening'
    | '/onboarding/diagnostic/reading'
    | '/onboarding/diagnostic/result'
    | '/onboarding/diagnostic/writing'
    | '/tests/$testId/results'
    | '/app/grammar/'
    | '/app/lexicon/'
    | '/app/session/'
    | '/onboarding/diagnostic/'
    | '/tests/$testId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AtlasRoute: typeof AtlasRoute
  LoginRoute: typeof LoginRoute
  MethodRoute: typeof MethodRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  StudyRoute: typeof StudyRoute
  TestsRoute: typeof TestsRouteWithChildren
  OnboardingBandRoute: typeof OnboardingBandRoute
  OnboardingDiagnosticRoute: typeof OnboardingDiagnosticRouteWithChildren
  PayPaymentIdRoute: typeof PayPaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/pay/$paymentId': {
      id: '/pay/$paymentId'
      path: '/pay/$paymentId'
      fullPath: '/pay/$paymentId'
      preLoaderRoute: typeof PayPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/diagnostic': {
      id: '/onboarding/diagnostic'
      path: '/onboarding/diagnostic'
      fullPath: '/onboarding/diagnostic'
      preLoaderRoute: typeof OnboardingDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/band': {
      id: '/onboarding/band'
      path: '/onboarding/band'
      fullPath: '/onboarding/band'
      preLoaderRoute: typeof OnboardingBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vocabulary': {
      id: '/app/vocabulary'
      path: '/vocabulary'
      fullPath: '/app/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/session': {
      id: '/app/session'
      path: '/session'
      fullPath: '/app/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lexicon': {
      id: '/app/lexicon'
      path: '/lexicon'
      fullPath: '/app/lexicon'
      preLoaderRoute: typeof AppLexiconRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grammar': {
      id: '/app/grammar'
      path: '/grammar'
      fullPath: '/app/grammar'
      preLoaderRoute: typeof AppGrammarRouteImport
      parentRoute: typeof AppRoute
    }
    '/tests/$testId/': {
      id: '/tests/$testId/'
      path: '/'
      fullPath: '/tests/$testId/'
      preLoaderRoute: typeof TestsTestIdIndexRouteImport
      parentRoute: typeof TestsTestIdRoute
    }
    '/onboarding/diagnostic/': {
      id: '/onboarding/diagnostic/'
      path: '/'
      fullPath: '/onboarding/diagnostic/'
      preLoaderRoute: typeof OnboardingDiagnosticIndexRouteImport
      parentRoute: typeof OnboardingDiagnosticRoute
    }
    '/app/session/': {
      id: '/app/session/'
      path: '/'
      fullPath: '/app/session/'
      preLoaderRoute: typeof AppSessionIndexRouteImport
      parentRoute: typeof AppSessionRoute
    }
    '/app/lexicon/': {
      id: '/app/lexicon/'
      path: '/'
      fullPath: '/app/lexicon/'
      preLoaderRoute: typeof AppLexiconIndexRouteImport
      parentRoute: typeof AppLexiconRoute
    }
    '/app/grammar/': {
      id: '/app/grammar/'
      path: '/'
      fullPath: '/app/grammar/'
      preLoaderRoute: typeof AppGrammarIndexRouteImport
      parentRoute: typeof AppGrammarRoute
    }
    '/tests/$testId/results': {
      id: '/tests/$testId/results'
      path: '/results'
      fullPath: '/tests/$testId/results'
      preLoaderRoute: typeof TestsTestIdResultsRouteImport
      parentRoute: typeof TestsTestIdRoute
    }
    '/onboarding/diagnostic/writing': {
      id: '/onboarding/diagnostic/writing'
      path: '/writing'
      fullPath: '/onboarding/diagnostic/writing'
      preLoaderRoute: typeof OnboardingDiagnosticWritingRouteImport
      parentRoute: typeof OnboardingDiagnosticRoute
    }
    '/onboarding/diagnostic/result': {
      id: '/onboarding/diagnostic/result'
      path: '/result'
      fullPath: '/onboarding/diagnostic/result'
      preLoaderRoute: typeof OnboardingDiagnosticResultRouteImport
      parentRoute: typeof OnboardingDiagnosticRoute
    }
    '/onboarding/diagnostic/reading': {
      id: '/onboarding/diagnostic/reading'
      path: '/reading'
      fullPath: '/onboarding/diagnostic/reading'
      preLoaderRoute: typeof OnboardingDiagnosticReadingRouteImport
      parentRoute: typeof OnboardingDiagnosticRoute
    }
    '/onboarding/diagnostic/listening': {
      id: '/onboarding/diagnostic/listening'
      path: '/listening'
      fullPath: '/onboarding/diagnostic/listening'
      preLoaderRoute: typeof OnboardingDiagnosticListeningRouteImport
      parentRoute: typeof OnboardingDiagnosticRoute
    }
    '/app/lexicon/$week': {
      id: '/app/lexicon/$week'
      path: '/$week'
      fullPath: '/app/lexicon/$week'
      preLoaderRoute: typeof AppLexiconWeekRouteImport
      parentRoute: typeof AppLexiconRoute
    }
    '/app/grammar/$week': {
      id: '/app/grammar/$week'
      path: '/$week'
      fullPath: '/app/grammar/$week'
      preLoaderRoute: typeof AppGrammarWeekRouteImport
      parentRoute: typeof AppGrammarRoute
    }
  }
}

interface AppGrammarRouteChildren {
  AppGrammarWeekRoute: typeof AppGrammarWeekRoute
  AppGrammarIndexRoute: typeof AppGrammarIndexRoute
}

const AppGrammarRouteChildren: AppGrammarRouteChildren = {
  AppGrammarWeekRoute: AppGrammarWeekRoute,
  AppGrammarIndexRoute: AppGrammarIndexRoute,
}

const AppGrammarRouteWithChildren = AppGrammarRoute._addFileChildren(
  AppGrammarRouteChildren,
)

interface AppLexiconRouteChildren {
  AppLexiconWeekRoute: typeof AppLexiconWeekRoute
  AppLexiconIndexRoute: typeof AppLexiconIndexRoute
}

const AppLexiconRouteChildren: AppLexiconRouteChildren = {
  AppLexiconWeekRoute: AppLexiconWeekRoute,
  AppLexiconIndexRoute: AppLexiconIndexRoute,
}

const AppLexiconRouteWithChildren = AppLexiconRoute._addFileChildren(
  AppLexiconRouteChildren,
)

interface AppSessionRouteChildren {
  AppSessionIndexRoute: typeof AppSessionIndexRoute
}

const AppSessionRouteChildren: AppSessionRouteChildren = {
  AppSessionIndexRoute: AppSessionIndexRoute,
}

const AppSessionRouteWithChildren = AppSessionRoute._addFileChildren(
  AppSessionRouteChildren,
)

interface AppRouteChildren {
  AppGrammarRoute: typeof AppGrammarRouteWithChildren
  AppLexiconRoute: typeof AppLexiconRouteWithChildren
  AppSessionRoute: typeof AppSessionRouteWithChildren
  AppVocabularyRoute: typeof AppVocabularyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGrammarRoute: AppGrammarRouteWithChildren,
  AppLexiconRoute: AppLexiconRouteWithChildren,
  AppSessionRoute: AppSessionRouteWithChildren,
  AppVocabularyRoute: AppVocabularyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TestsTestIdRouteChildren {
  TestsTestIdResultsRoute: typeof TestsTestIdResultsRoute
  TestsTestIdIndexRoute: typeof TestsTestIdIndexRoute
}

const TestsTestIdRouteChildren: TestsTestIdRouteChildren = {
  TestsTestIdResultsRoute: TestsTestIdResultsRoute,
  TestsTestIdIndexRoute: TestsTestIdIndexRoute,
}

const TestsTestIdRouteWithChildren = TestsTestIdRoute._addFileChildren(
  TestsTestIdRouteChildren,
)

interface TestsRouteChildren {
  TestsTestIdRoute: typeof TestsTestIdRouteWithChildren
  TestsIndexRoute: typeof TestsIndexRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsTestIdRoute: TestsTestIdRouteWithChildren,
  TestsIndexRoute: TestsIndexRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

interface OnboardingDiagnosticRouteChildren {
  OnboardingDiagnosticListeningRoute: typeof OnboardingDiagnosticListeningRoute
  OnboardingDiagnosticReadingRoute: typeof OnboardingDiagnosticReadingRoute
  OnboardingDiagnosticResultRoute: typeof OnboardingDiagnosticResultRoute
  OnboardingDiagnosticWritingRoute: typeof OnboardingDiagnosticWritingRoute
  OnboardingDiagnosticIndexRoute: typeof OnboardingDiagnosticIndexRoute
}

const OnboardingDiagnosticRouteChildren: OnboardingDiagnosticRouteChildren = {
  OnboardingDiagnosticListeningRoute: OnboardingDiagnosticListeningRoute,
  OnboardingDiagnosticReadingRoute: OnboardingDiagnosticReadingRoute,
  OnboardingDiagnosticResultRoute: OnboardingDiagnosticResultRoute,
  OnboardingDiagnosticWritingRoute: OnboardingDiagnosticWritingRoute,
  OnboardingDiagnosticIndexRoute: OnboardingDiagnosticIndexRoute,
}

const OnboardingDiagnosticRouteWithChildren =
  OnboardingDiagnosticRoute._addFileChildren(OnboardingDiagnosticRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AtlasRoute: AtlasRoute,
  LoginRoute: LoginRoute,
  MethodRoute: MethodRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  StudyRoute: StudyRoute,
  TestsRoute: TestsRouteWithChildren,
  OnboardingBandRoute: OnboardingBandRoute,
  OnboardingDiagnosticRoute: OnboardingDiagnosticRouteWithChildren,
  PayPaymentIdRoute: PayPaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
