/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MethodRouteImport } from './routes/method'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'
import { Route as OnboardingBandRouteImport } from './routes/onboarding.band'
import { Route as AppVocabularyRouteImport } from './routes/app.vocabulary'
import { Route as AppSessionRouteImport } from './routes/app.session'
import { Route as AppNotebookRouteImport } from './routes/app.notebook'
import { Route as AppGrammarRouteImport } from './routes/app.grammar'
import { Route as TestsTestIdIndexRouteImport } from './routes/tests.$testId.index'
import { Route as AppSessionIndexRouteImport } from './routes/app.session.index'
import { Route as TestsTestIdResultsRouteImport } from './routes/tests.$testId.results'
import { Route as AppSessionCompleteRouteImport } from './routes/app.session.complete'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => TestsRoute,
} as any)
const OnboardingBandRoute = OnboardingBandRouteImport.update({
  id: '/onboarding/band',
  path: '/onboarding/band',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVocabularyRoute = AppVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppNotebookRoute = AppNotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => AppRoute,
} as any)
const AppGrammarRoute = AppGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AppRoute,
} as any)
const TestsTestIdIndexRoute = TestsTestIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsTestIdRoute,
} as any)
const AppSessionIndexRoute = AppSessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSessionRoute,
} as any)
const TestsTestIdResultsRoute = TestsTestIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TestsTestIdRoute,
} as any)
const AppSessionCompleteRoute = AppSessionCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => AppSessionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/tests': typeof TestsRouteWithChildren
  '/app/grammar': typeof AppGrammarRoute
  '/app/notebook': typeof AppNotebookRoute
  '/app/session': typeof AppSessionRouteWithChildren
  '/app/vocabulary': typeof AppVocabularyRoute
  '/onboarding/band': typeof OnboardingBandRoute
  '/tests/$testId': typeof TestsTestIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/app/session/complete': typeof AppSessionCompleteRoute
  '/tests/$testId/results': typeof TestsTestIdResultsRoute
  '/app/session/': typeof AppSessionIndexRoute
  '/tests/$testId/': typeof TestsTestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/app/grammar': typeof AppGrammarRoute
  '/app/notebook': typeof AppNotebookRoute
  '/app/vocabulary': typeof AppVocabularyRoute
  '/onboarding/band': typeof OnboardingBandRoute
  '/app': typeof AppIndexRoute
  '/tests': typeof TestsIndexRoute
  '/app/session/complete': typeof AppSessionCompleteRoute
  '/tests/$testId/results': typeof TestsTestIdResultsRoute
  '/app/session': typeof AppSessionIndexRoute
  '/tests/$testId': typeof TestsTestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/tests': typeof TestsRouteWithChildren
  '/app/grammar': typeof AppGrammarRoute
  '/app/notebook': typeof AppNotebookRoute
  '/app/session': typeof AppSessionRouteWithChildren
  '/app/vocabulary': typeof AppVocabularyRoute
  '/onboarding/band': typeof OnboardingBandRoute
  '/tests/$testId': typeof TestsTestIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/app/session/complete': typeof AppSessionCompleteRoute
  '/tests/$testId/results': typeof TestsTestIdResultsRoute
  '/app/session/': typeof AppSessionIndexRoute
  '/tests/$testId/': typeof TestsTestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/method'
    | '/profile'
    | '/signup'
    | '/study'
    | '/tests'
    | '/app/grammar'
    | '/app/notebook'
    | '/app/session'
    | '/app/vocabulary'
    | '/onboarding/band'
    | '/tests/$testId'
    | '/app/'
    | '/tests/'
    | '/app/session/complete'
    | '/tests/$testId/results'
    | '/app/session/'
    | '/tests/$testId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/method'
    | '/profile'
    | '/signup'
    | '/study'
    | '/app/grammar'
    | '/app/notebook'
    | '/app/vocabulary'
    | '/onboarding/band'
    | '/app'
    | '/tests'
    | '/app/session/complete'
    | '/tests/$testId/results'
    | '/app/session'
    | '/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/method'
    | '/profile'
    | '/signup'
    | '/study'
    | '/tests'
    | '/app/grammar'
    | '/app/notebook'
    | '/app/session'
    | '/app/vocabulary'
    | '/onboarding/band'
    | '/tests/$testId'
    | '/app/'
    | '/tests/'
    | '/app/session/complete'
    | '/tests/$testId/results'
    | '/app/session/'
    | '/tests/$testId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MethodRoute: typeof MethodRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  StudyRoute: typeof StudyRoute
  TestsRoute: typeof TestsRouteWithChildren
  OnboardingBandRoute: typeof OnboardingBandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/onboarding/band': {
      id: '/onboarding/band'
      path: '/onboarding/band'
      fullPath: '/onboarding/band'
      preLoaderRoute: typeof OnboardingBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vocabulary': {
      id: '/app/vocabulary'
      path: '/vocabulary'
      fullPath: '/app/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/session': {
      id: '/app/session'
      path: '/session'
      fullPath: '/app/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notebook': {
      id: '/app/notebook'
      path: '/notebook'
      fullPath: '/app/notebook'
      preLoaderRoute: typeof AppNotebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grammar': {
      id: '/app/grammar'
      path: '/grammar'
      fullPath: '/app/grammar'
      preLoaderRoute: typeof AppGrammarRouteImport
      parentRoute: typeof AppRoute
    }
    '/tests/$testId/': {
      id: '/tests/$testId/'
      path: '/'
      fullPath: '/tests/$testId/'
      preLoaderRoute: typeof TestsTestIdIndexRouteImport
      parentRoute: typeof TestsTestIdRoute
    }
    '/app/session/': {
      id: '/app/session/'
      path: '/'
      fullPath: '/app/session/'
      preLoaderRoute: typeof AppSessionIndexRouteImport
      parentRoute: typeof AppSessionRoute
    }
    '/tests/$testId/results': {
      id: '/tests/$testId/results'
      path: '/results'
      fullPath: '/tests/$testId/results'
      preLoaderRoute: typeof TestsTestIdResultsRouteImport
      parentRoute: typeof TestsTestIdRoute
    }
    '/app/session/complete': {
      id: '/app/session/complete'
      path: '/complete'
      fullPath: '/app/session/complete'
      preLoaderRoute: typeof AppSessionCompleteRouteImport
      parentRoute: typeof AppSessionRoute
    }
  }
}

interface AppSessionRouteChildren {
  AppSessionCompleteRoute: typeof AppSessionCompleteRoute
  AppSessionIndexRoute: typeof AppSessionIndexRoute
}

const AppSessionRouteChildren: AppSessionRouteChildren = {
  AppSessionCompleteRoute: AppSessionCompleteRoute,
  AppSessionIndexRoute: AppSessionIndexRoute,
}

const AppSessionRouteWithChildren = AppSessionRoute._addFileChildren(
  AppSessionRouteChildren,
)

interface AppRouteChildren {
  AppGrammarRoute: typeof AppGrammarRoute
  AppNotebookRoute: typeof AppNotebookRoute
  AppSessionRoute: typeof AppSessionRouteWithChildren
  AppVocabularyRoute: typeof AppVocabularyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGrammarRoute: AppGrammarRoute,
  AppNotebookRoute: AppNotebookRoute,
  AppSessionRoute: AppSessionRouteWithChildren,
  AppVocabularyRoute: AppVocabularyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TestsTestIdRouteChildren {
  TestsTestIdResultsRoute: typeof TestsTestIdResultsRoute
  TestsTestIdIndexRoute: typeof TestsTestIdIndexRoute
}

const TestsTestIdRouteChildren: TestsTestIdRouteChildren = {
  TestsTestIdResultsRoute: TestsTestIdResultsRoute,
  TestsTestIdIndexRoute: TestsTestIdIndexRoute,
}

const TestsTestIdRouteWithChildren = TestsTestIdRoute._addFileChildren(
  TestsTestIdRouteChildren,
)

interface TestsRouteChildren {
  TestsTestIdRoute: typeof TestsTestIdRouteWithChildren
  TestsIndexRoute: typeof TestsIndexRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsTestIdRoute: TestsTestIdRouteWithChildren,
  TestsIndexRoute: TestsIndexRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MethodRoute: MethodRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  StudyRoute: StudyRoute,
  TestsRoute: TestsRouteWithChildren,
  OnboardingBandRoute: OnboardingBandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
